[book]
authors = ["wabisabia"]
language = "en"
multilingual = false
src = "src"
title = "Revision"

[output.html]
mathjax-support = true
default-theme = "ayu"
preferred-dark-theme = "ayu"

[output.html.fold]
enable = true